(library
 (name npm_frontend)
 (wrapped false)
 (modules npm_version npm_parse)
 (libraries version yojson))

(library
 (name npm_solve)
 (modules encoding archive query lookup pick order solve print)
 (private_modules encoding lookup pick order)
 (libraries npm_frontend pac pac_common pubgrub unix yojson))

(test
 (name test_npm_version)
 (modules test_npm_version)
 (libraries npm_frontend))
