(library
 (name alpine_frontend)
 (wrapped false)
 (modules apk_version apk_parse))

(library
 (name alpine_solve)
 (modules lookups order alpine_solve)
 (libraries alpine_frontend pac pac_common package_formula pubgrub))

(test
 (name test_apk_version)
 (modules test_apk_version)
 (libraries alpine_frontend))
