(library
 (name cargo_frontend)
 (wrapped false)
 (modules cargo_version cargo_parse cargo_toml cargo_query)
 (libraries version yojson))

(library
 (name cargo_solve)
 (modules archive encoding lookups order pick cargo_solve)
 (libraries cargo_frontend pac pac_common pubgrub unix))

(test
 (name test_cargo_version)
 (modules test_cargo_version)
 (libraries cargo_frontend))

(test
 (name test_cargo_solve)
 (modules test_cargo_solve)
 (deps
  (source_tree ../../test/frontends/cargo.t))
 (libraries cargo_frontend cargo_solve))
